
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
    key: server
    paths:
      - cache/

before_script:
  - apt update
  - apt -y install software-properties-common
  - add-apt-repository -r ppa:deadsnakes/ppa
  - apt-get update
  - apt -y install python3
  - python3 -V
  - apt -y install python3-pip
  - cd server  # Print out python version for debugging
  - pip3 install --upgrade pip
  - pip3 install --upgrade setuptools
  - pip3 install -r requirements.txt
  - cd ..

flake8:
  stage: style
  script:
    - cd server
    - flake8 --verbose .
  allow_failure: true
  cache:
    key: server
    paths:
      - cache/

backend test:
  stage: test
  script:
    - cd server
    - pytest
  cache:
    key: server
    paths:
      - cache/




